# Generated by Django 2.0.2 on 2018-03-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]


    operations = [
        migrations.CreateModel(
            name='educate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educate_id', models.CharField(max_length=8)),
                ('educate_degree', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='seek',
            fields=[
                ('seek_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('seek_title', models.CharField(max_length=32)),
                ('seek_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=16)),
                ('user_password', models.CharField(max_length=16)),
                ('user_sex', models.CharField(choices=[(0, 'M'), (1, 'W'), (2, 'X')], default='X', max_length=1)),
                ('user_phone', models.CharField(max_length=11)),
                ('user_educate_id', models.CharField(max_length=8)),
                ('user_level_id', models.CharField(max_length=8)),
                ('user_intr_id', models.CharField(max_length=8)),
                ('user_status_id', models.CharField(max_length=8)),
                ('user_company_id', models.CharField(max_length=8)),
            ],
        ),
    ]
