# Generated by Django 2.0.2 on 2018-04-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_status',
            name='task_status_agree_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='task_status_apply_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='task_status_begin_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='task_status_finish_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='task_status_is_agree',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='task_status_is_apply',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='task_status_is_begin',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='task_status_is_end',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
