# Generated by Django 2.0.2 on 2018-04-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
