# Generated by Django 2.0.2 on 2018-04-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180427_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_status',
            name='task_status_is_agree',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='task_status_is_apply',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='task_status_is_begin',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='task_status_is_end',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
