# Generated by Django 2.0.2 on 2018-04-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180424_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_applyer_id',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_info',
            field=models.TextField(null=True),
        ),
    ]
